window:
    dynamic_padding: true
    title: Terminal
    dynamic_title: true

alt_send_esc: false

font:
  size: 14
  family: monospace
  use_thin_strokes: true

colors:
  primary:
    background: '0x282828'
    foreground: '0xdfbf8e'

  normal:
    black:   '0x665c54'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xe78a4e'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xdfbf8e'

  bright:
    black:   '0x928374'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xe3a84e'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xdfbf8e'

key_bindings:
  - { key: K,              mods: Command, mode: ~Vi|~Search, chars: "\x0c"                 }
  - { key: K,              mods: Command, mode: ~Vi|~Search, action: ClearHistory          }
  - { key: Key0,           mods: Command,                    action: ResetFontSize         }
  - { key: Equals,         mods: Command,                    action: IncreaseFontSize      }
  - { key: Plus,           mods: Command,                    action: IncreaseFontSize      }
  - { key: NumpadAdd,      mods: Command,                    action: IncreaseFontSize      }
  - { key: Minus,          mods: Command,                    action: DecreaseFontSize      }
  - { key: NumpadSubtract, mods: Command,                    action: DecreaseFontSize      }
  - { key: V,              mods: Command,                    action: Paste                 }
  - { key: C,              mods: Command,                    action: Copy                  }
  - { key: C,              mods: Command, mode: Vi|~Search,  action: ClearSelection        }
  - { key: H,              mods: Command,                    action: Hide                  }
  - { key: H,              mods: Command|Alt,                action: HideOtherApplications }
  - { key: M,              mods: Command,                    action: Minimize              }
  - { key: Q,              mods: Command,                    action: Quit                  }
  - { key: W,              mods: Command,                    action: Quit                  }
  - { key: N,              mods: Command,                    action: SpawnNewInstance      }
  - { key: F,              mods: Command|Control,            action: ToggleFullscreen      }
  - { key: F,              mods: Command, mode: ~Search,     action: SearchForward         }
  - { key: B,              mods: Command, mode: ~Search,     action: SearchBackward        }
