env:
    TERM: alacritty

window:
    dynamic_padding: true

alt_send_esc: false

font:
  size: 13
  family: monospace
  use_thin_strokes: true


# Colors (Doom One)
colors:
  # Default colors
  primary:
    background: '0x282c34'
    foreground: '0xbbc2cf'

  # Normal colors
  normal:
    black:   '0x282c34'
    red:     '0xff6c6b'
    green:   '0x98be65'
    yellow:  '0xecbe7b'
    blue:    '0x51afef'
    magenta: '0xc678dd'
    cyan:    '0x46d9ff'
    white:   '0xbbc2cf'
